version: '3'

services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: <db-name>
      POSTGRES_USER: <db-user>
      POSTGRES_PASSWORD: <db-password>

  backend:
    image: dimmaryanto93/udemy-springboot-app:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: <db-name>
      DATABASE_USERNAME: <db-user>
      DATABASE_PASSWORD: <db-password>
      APPLICATION_PORT: 8080
    depends_on:
      - postgres

  frontend:
    image: dimmaryanto93/udemy-angular-app:latest
    ports:
      - "80:80"
    environment:
      APPLICATION_PORT: 80
      NGINX_ROOT_DOCUMENT: /var/www/html
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
      BACKEND_CONTEXT_PATH: /
    depends_on:
      - backend
